---
language: node_js
node_js:
  - "10"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - "FTP_USER=[ftp-user]"
    - "FTP_PASSWORD=[ftp-password]"
    - "FTP_URL=[ftp-url]"

branches:
  only:
    - master

before_script:
  - npm install -g hexo-cli

script:
  - hexo init tmp-blog
  - bash .travis/pull_data.sh
  - bash .travis/deploy.sh
